name: netflix_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material3_layout: ^0.0.1
  get: 

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  firebase_storage: ^11.2.6
  path_provider: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts: 
      - asset: assets/SFPRODISPLAYREGULAR.OTF
